//TODO: components
var vm = new Vue({
    el: '#songlist',
    data: {
        songs: [
            {title: "Take On Me", artist: "a-ha"},
            {title: "Dear Maria, Count Me In", artist: "All Time Low"},
            {title: "Dirty Little Secret", artist: "The All-American Rejects"},
            {title: "Sail", artist: "AWOLNATION"},
            {title: "Hard to Handle", artist: "The Black Crowes"},
            {title: "Gold On The Ceiling", artist: "The Black Keys"},
            {title: "Dammit", artist: "blink-182"},
            {title: "All The Small Things", artist: "blink-182"},
            {title: "I Melt With You", artist: "Bowling For Soup"},
            {title: "1985", artist: "Bowling For Soup"},
            {title: "In One Ear", artist: "Cage The Elephant"},
            {title: "Closer", artist: "The Chainsmokers"},
            {title: "Shout", artist: "Otis Day and the Knights"},
            {title: "I Found A Way", artist: "Drake Bell"},
            {title: "Inside Out", artist: "Eve 6"},
            {title: "Sugar, We're Goin Down", artist: "Fall Out Boy"},
            {title: "Stacy's Mom", artist: "Fountains Of Wayne"},
            {title: "99 Red Balloons", artist: "Goldfinger"},
            {title: "The Anthem", artist: "Good Charlotte"},
            {title: "Holiday", artist: "Green Day"},
            {title: "American Woman", artist: "The Guess Who"},
            {title: "Sweet Child O' Mine", artist: "Guns N' Roses"},
            {title: "Are You Gonna Be My Girl", artist: "Jet"},
            {title: "Cold Hard Bitch", artist: "Jet"},
            {title: "The Middle", artist: "Jimmy Eat World"},
            {title: "Erase Me - Main", artist: "Kid Cudi, Kanye West"},
            {title: "Mr. Brightside", artist: "The Killers"},
            {title: "When You Were Young", artist: "The Killers"},
            {title: "My Own Worst Enemy", artist: "Lit"},
            {title: "Scotty Doesn't Know", artist: "Lustra"},
            {title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd"},
            {title: "3AM", artist: "Matchbox Twenty"},
            {title: "Teenagers", artist: "My Chemical Romance"},
            {title: "Everybody Talks", artist: "Neon Trees"},
            {title: "Absolutely (Story of a Girl)", artist: "Nine Days"},
            {title: "Little Talks", artist: "Of Monsters and Men"},
            {title: "I Write Sins Not Tragedies", artist: "Panic! At The Disco"},
            {title: "Bulls On Parade", artist: "Rage Against The Machine"},
            {title: "Killing In The Name", artist: "Rage Against The Machine"},
            {title: "Dani California", artist: "Red Hot Chili Peppers"},
            {title: "Face Down", artist: "The Red Jumpsuit Apparatus"},
            {title: "All Star", artist: "Smash Mouth"},
            {title: "Born To Be Wild", artist: "Steppenwolf"},
            {title: "Semi-Charmed Life", artist: "Third Eye Blind"},
            {title: "You Really Got Me", artist: "Van Halen"},
            {title: "Teenage Dirtbag", artist: "Wheatus"},
            {title: "Seven Nation Army", artist: "The White Stripes"},
            {title: "Play That Funky Music", artist: "Wild Cherry"}
        ]
    }
})
